config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  get 'calendar', to: 'calendar#show'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users 
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :users do 
  resource :events
  end
  
  get 'users/:user_id/events/new', to: 'events#create'
    
end
  
 

app/models/event.rb
class Event < ActiveRecord::Base
     # scope :between, lambda {|start_time, end_time| {:conditions => ["? < starts_at and starts_at < ?", Event.format_date(start_time), Event.format_date(end_time)] }}
   
  belongs_to :user 
  
  def self.between(start_time, end_time)
    where('start_time > :lo and start_time < :up',
      :lo => Event.format_date(start_time),
      :up => Event.format_date(end_time)
    )
  end

  def self.format_date(date_time)
   Time.at(date_time.to_i).to_formatted_s(:db)
  end

  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :start => self.start_time,
      :end => self.end_time,
      :description => self.description,
      :allDay => allday,
      :url => Rails.application.routes.url_helpers.calendar_path(id),
      :color => "green"
    }
  end
  
  private

    def finish_cannot_be_earlier_than_start
      unless start.nil? || finish.nil?
        time_error if finish < start
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
     
     
     has_many :events, dependent: :delete_all
     before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end
  
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @events = Event.all
  	respond_to do |format|
  		format.html
  		format.json { render json: @events}
  	end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  
  # GET /events
  # GET /events.json
  def index
    
    @events = Event.all
    @events = @events.between(params['start'], params['end']) 
    if  (params['start'] && params['end'])
    @events = @events.for_user(params[:user_id]) 
    if params[:user_id].present? && params[:user_id] == current_user.id
    respond_to do |format|
    format.html # index.html.erb
    format.json { render json:  @events.to_json(:include => :user) }
    end
    end
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.find(params[:user_id])
    render json: @events.to_json(:include => :user)
  end
  
  

  # GET /events/new
  def new
    @event = Event.new(params[:user])
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.create(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to calendar_path, alert: "登録完了！！" }
        format.js   {}
        format.json { render json: @event, :formats => [:json], :handlers => [:jbuilder] }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = Event.update(params[:user_id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.destroy(params[:user_id])
    
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
      @user.destroy
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = '登録したメールアドレス・パスワードが一致しません'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "会員登録が完了しました"
    else
      render 'new'
    end
  end
  
  def show 
    @user = User.find(params[:id])
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update #課題
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_url(@user) ,notice: 'プロフィールを更新しました。'
    else
       flash.now[:alert] = "プロフィールに不備がある為、更新に失敗しました。"
       render 'edit'
    end
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/views/calendar/index.html.erb
<div id="calendar"></div>
<style>
.fc-sun { color: red; } /* 日曜日 */
.fc-sat { color: blue; } /* 土曜日 */

</style>

app/views/calendar/show.html.erb
<div id="calendar"></div>
<style>
.fc-sun { color: red; } /* 日曜日 */
.fc-sat { color: blue; } /* 土曜日 */

</style>

app/views/events/_form.html.erb
<%= form_for@event, method: "POST",:url => { :action => :create } do |f| %>

  <div class="field">
    <%= f.label :タイトル %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :内容 %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :開始時刻 %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :終了時刻 %><br>
    <%= f.datetime_select :end_time %>
  </div></br>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>登録内容一覧</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>開始時刻</th>
      <th>終了時刻</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <% @events.each do |event| %>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= link_to '表示', edit_user_events %></td>
        <td><%= link_to '編集', edit_user_events_path(event) %></td>
        <td><%= link_to '削除', edit_user_events_path, method: :destroy, data: { confirm: '削除していいですか?' } %></td>
      </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しい家事分担を登録', new_user_events_path(current_user) %>

app/views/events/new.html.erb
<h1>家事分担登録</h1>

<%= render 'form' %>

<%= link_to '戻る', '#' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>内容:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>開始時刻:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>終了時刻:</strong>
  <%= @event.end_time %>
</p>

<%= link_to '編集画面に戻る', edit_event_path(@event) %> |
<%= link_to '登録内容一覧', events_path %>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Home", root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
         <ul class="nav navbar-nav navbar-right">
          <% unless logged_in? %>
            <li><%= link_to "新規登録", signup_path %></li>
            <li><%= link_to "ログイン", login_path %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">家事分担管理<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "カレンダー表示", calendar_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "家事分担登録画面", new_user_events_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "日", '#' %></li>
              </ul>
            </li>
            <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "プロフィール", current_user %></li>
                <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "ログアウト", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% end %>
         </ul>  
        </div>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharekarji</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/header" %>
<div class="container">
  <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> <!-- ここまで追加 -->
    
  <%= yield %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container-fluid">
	<div class="row">
        <div class="col-sm-8"><h1><%= @user.name %>さんのプロフィール編集</h1></div>
    </div>
</div> 

<div class="form-horizontal" role="form">
    <%= form_for(@user) do |f| %>

  <div class="form-group">
   <label for="inputname" class="col-sm-2 control-label">名前：</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div> 
  </div>

 <div class="form-group">
   <label for="inputemail" class="col-sm-2 control-label">メールアドレス：</label>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div> 
 </div>

 <div class="form-group">
   <label for="inputname" class="col-sm-2 control-label">パートナー名：</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div> 
  </div>
      
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "更新", class: "btn btn-primary" %>
   </div> 
 </div>
 <% end %>
 </div> 
 </div>           
    

app/views/users/new.html.erb
<h2>会員登録</h2>

<div class="form-horizontal" role="form">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

 <div class="form-group">
   <label for="inputname" class="col-sm-2 control-label">名前：</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div> 
 </div>
 
 <div class="form-group">
   <label for="inputemail" class="col-sm-2 control-label">メールアドレス：</label>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div> 
 </div>
 
 <div class="form-group">
   <label for="inputpassword" class="col-sm-2 control-label">パスワード：</label>
   <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div> 
 </div> 

 <div class="form-group">
   <label for="password_confirmation" class="col-sm-2 control-label">パスワード(再入力)：</label>
   <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
   </div> 
 </div>   

 <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "登録", class: "btn btn-large btn-primary" %>
    <% end %>
   </div> 
 </div>  

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %>の基本情報</h1>
    </section>
  </aside>    
</div>

<div class="form-horizontal" role="form">
    <%= form_for(@user) do |f| %>

  <div class="form-group">
   <label for="inputname" class="col-sm-2 control-label">名前：</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div> 
  </div>

 <div class="form-group">
   <label for="inputemail" class="col-sm-2 control-label">メールアドレス：</label>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div> 
 </div>

 <div class="form-group">
   <label for="inputname" class="col-sm-2 control-label">パートナー名：</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div> 
  </div>
 
 <% end %>
 </div> 
 </div>          

app/views/welcome/index.html.erb
<div class="jumbotron">
    <div class="container">
        <img src="<%= asset_path "photo.jpg" %>" />
        <div style="background-image:url(<%= asset_path "photo.jpg" %>)" />
        </div>
    </div>
</div>